### ISSUE TITLE
Ability to rotate light cones.

### ISSUE THREAD

**Issue by SirAron111** [kandashi/Active-Token-Lighting#129]
**Is your feature request related to a problem? Please describe.**
Is it possible to have light cones to be rotated or flipped by a certain angle, so they emit the other direction without turning the token around or upside down? [...]

**Describe the solution you'd like**
ability to flip light emitting direction when not using a full circle (a bulls eye lantern for example, a lighthouse or something like a spotlight).

**Describe alternatives you've considered**
Flipping the tokens upside down is annoying.

**Additional context**
not really, just a mirror light function would be enough or a light direction option etc.

**Comment by kaelad02** [comment]
Changing the orientation of an angled light is beyond this module's scope. Plus, how would we know when to do this since some tokens may already be facing down? But there is a workaround. You could flip the token image vertically so they'd be facing down. You could do this in one of two ways:

1. Change the token's properties manually ahead of time by checking the Mirror Image (Vertically) box
2. Add another change line to your effect to flip it: `ATL.mirrorY | Override | true`
