### ISSUE TITLE
use meters instead of feets

### ISSUE THREAD

**Issue by CaosFR** [kandashi/Active-Token-Lighting#156]
**Is your feature request related to a problem? Please describe.**
I'm not use feet but meter for distance calculing

**Describe the solution you'd like**
Premades effects in the ATL compendium ("ATL.light.dim" and "ATL.light.bright") are set in feet 

**Describe alternatives you've considered**
A option to transform all feet reference to meter

**Additional context**
Thanks

Of course I could modify the compendium, but with each update this will be lost.

**Comment by kaelad02** [comment]
While the dnd5e system, what those premade items are for, has an option to use metric weights, it doesn't change the items in the SRD compendium packs. While I see the convenience of being able to adjust weights of items in the pack, that sounds out of scope for this module to add. Meaning, this feature should be in the system or a separate module that can change the weights of the items in all compendium packs. Building that feature into this module to only adjust its items doesn't sound as useful since other packs also need adjusting.
