### ISSUE TITLE
meny minor error and preset error.

### ISSUE THREAD

**Issue by rinnocenti** [kandashi/Active-Token-Lighting#50]
![image](https://user-images.githubusercontent.com/3178127/120910486-b4a27e80-c655-11eb-9758-854680f5c7d2.png)
several warnings of deprecated commands, and using the torch preset it gives an error, it works the first 2 .. 3 times and then it doesn't activate anymore.

**Comment by kandashi** [comment]
I'll take a look

**Comment by kandashi** [comment]
From what I can tell, none of those come from ATL, and I cannot replicate the torch issues

**Comment by Th3Rom3** [comment]
Most of these error seem to be caused by Token Action Hud and not the ATL module.

With only ATL active I don't get any errors in console at all for the following config:

local foundry 0.8.6 setup on node.js 14.17; DnD5e 1.3.3 and ATL 0.2.14

The only quirk I encounter is a red popup box reading "ATL: preset string error" whenever I use one of the presets from the compendium. Otherwise it works fine and the popup does not seem to cause any trouble itself.
